* Commentary

 - Bitcoin donations gratefully accepted :: 12k9zUo9Dgqk8Rary2cuzyvAQWD5EAuZ4q

This file contains various helper functions for handling symbols. 
The code originally comes from chapter 4.7 of onlisp by Paul Graham:
http://www.bookshelf.jp/texi/onlisp/onlisp_5.html#SEC35

* Functions

 - mkstr : Make a string from the list of `args'. Each arg can be a string or a symbol.
 - symb : Make a symbol from the list of `args'. Each arg can be a string or a symbol.
 - reread : Make a symbol from the list of `args'. Each arg can be a string or a symbol.
 - explode : Given symbol `sym', return a list of symbols for the individual chars making up `sym'.
 - get-matching-symbols : Return a list of all symbols in `obary' whose names match the regular expression `regex'.
 - unintern-matching-symbols : Remove all symbols whose name matches `regex' from the obarray `obary'.

* Installation

Put symbol-tools.el in a directory in your load-path, e.g. ~/.emacs.d/
You can add a directory to your load-path with the following line in ~/.emacs
(add-to-list 'load-path (expand-file-name "~/elisp"))
where ~/elisp is the directory you want to add 
(you don't need to do this for ~/.emacs.d - it's added by default).

Add the following to your ~/.emacs startup file.

(require 'symbol-tools)

